chore: updating dependabot to support TS, JS, Python, dev container and docker packages
rajpalc7/aries-mediator-service pull request #1
Opened 2024-05-10 18:58 UTC by rajpalc7

2024-05-10 19:00 UTC, rajpalc7 commented
Hi @wadebarnes, this is ready for review now.

2024-05-10 20:10 UTC, WadeBarnes requested changes
@rajpalc7, It looks like you're missing one dependency file.

2024-05-10 20:35 UTC, rajpalc7 commented
Thanks @WadeBarnes , I have added one file now.

2024-05-13 13:17 UTC, WadeBarnes approved these changes

2024-05-17 16:15 UTC, closed without merging